// GENERATED by scripts/set_version.py — do not edit by hand.
/// Canonical application version, stamped by CI from the release input.
const String kAppVersion = '0.1.0';
const int kAppVersionMajor = 0;
const int kAppVersionMinor = 1;
const int kAppVersionPatch = 0;
