#!/usr/bin/env python3
"""Propagate a release version to every versioned surface of IranLink.

Updated atoms (must stay in sync — enforced by scripts/check_version.py):
  pubspec.yaml                      -> version: X.Y.Z(+build, preserved)
  windows/runner/Runner.rc          -> FILEVERSION/PRODUCTVERSION + strings
  installer/iranlink.iss            -> #define MyAppVersion "X.Y.Z"
  lib/src/core/app_version.dart     -> generated const (About screen, UA, ...)
  CHANGELOG.md                      -> Unreleased section gets a version stamp line

Usage: python scripts/set_version.py --version 1.4.2 [--root .]
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from validate_version import parse as parse_version  # noqa: E402


def _replace(path: Path, pattern: str, repl: str, count: int = 1) -> None:
    text = path.read_text(encoding="utf-8")
    new, n = re.subn(pattern, repl, text, count=count, flags=re.M)
    if n != count:
        raise SystemExit(f"ERROR: pattern not found {count}x in {path}: {pattern!r}")
    path.write_text(new, encoding="utf-8")


def set_pubspec(root: Path, version: str) -> None:
    p = root / "pubspec.yaml"
    text = p.read_text(encoding="utf-8")
    m = re.search(r"^version:\s*(\S+)\s*$", text, re.M)
    if not m:
        raise SystemExit("ERROR: no version: line in pubspec.yaml")
    build = ""
    if "+" in m.group(1):
        build = "+" + m.group(1).split("+", 1)[1]
    _replace(p, r"^version:\s*\S+\s*$", f"version: {version}{build}", count=1)
    print(f"  pubspec.yaml -> {version}{build}")


def set_runner_rc(root: Path, version: str) -> None:
    major, minor, patch = parse_version(version)
    p = root / "windows" / "runner" / "Runner.rc"
    dotted = f"{major},{minor},{patch},0"
    _replace(p, r"FILEVERSION \d+,\d+,\d+,\d+", f"FILEVERSION {dotted}")
    _replace(p, r"PRODUCTVERSION \d+,\d+,\d+,\d+", f"PRODUCTVERSION {dotted}")
    _replace(p, r'VALUE "FileVersion", "[^"]*"', f'VALUE "FileVersion", "{version}"')
    _replace(p, r'VALUE "ProductVersion", "[^"]*"', f'VALUE "ProductVersion", "{version}"')
    print(f"  Runner.rc -> {version}")


def set_iss(root: Path, version: str) -> None:
    p = root / "installer" / "iranlink.iss"
    _replace(p, r'#define MyAppVersion "[^"]*"', f'#define MyAppVersion "{version}"')
    print(f"  iranlink.iss -> {version}")


def set_app_version_dart(root: Path, version: str) -> None:
    major, minor, patch = parse_version(version)
    p = root / "lib" / "src" / "core" / "app_version.dart"
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(
        "// GENERATED by scripts/set_version.py — do not edit by hand.\n"
        "/// Canonical application version, stamped by CI from the release input.\n"
        f"const String kAppVersion = '{version}';\n"
        f"const int kAppVersionMajor = {major};\n"
        f"const int kAppVersionMinor = {minor};\n"
        f"const int kAppVersionPatch = {patch};\n",
        encoding="utf-8",
    )
    print(f"  app_version.dart -> {version}")


def set_changelog(root: Path, version: str) -> None:
    p = root / "CHANGELOG.md"
    text = p.read_text(encoding="utf-8")
    marker = "## [Unreleased]"
    if marker not in text:
        raise SystemExit("ERROR: CHANGELOG.md has no ## [Unreleased] section")
    stamp = f"{marker}\n\n> Release in progress: {version} (stamped by CI)."
    if "Release in progress:" in text:
        text = re.sub(r"> Release in progress: .*", f"> Release in progress: {version} (stamped by CI).", text, count=1)
    else:
        text = text.replace(marker, stamp, 1)
    p.write_text(text, encoding="utf-8")
    print(f"  CHANGELOG.md -> {version}")


def set_all(root: Path, version: str) -> None:
    parse_version(version)  # fail fast on invalid input
    print(f"Stamping version {version}:")
    set_pubspec(root, version)
    set_runner_rc(root, version)
    set_iss(root, version)
    set_app_version_dart(root, version)
    set_changelog(root, version)


def self_test() -> None:
    import tempfile
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        (root / "pubspec.yaml").write_text("name: iranlink\nversion: 0.1.0+1\n", encoding="utf-8")
        rc = root / "windows" / "runner"
        rc.mkdir(parents=True)
        (rc / "Runner.rc").write_text(
            'FILEVERSION 0,1,0,0\nPRODUCTVERSION 0,1,0,0\n'
            'VALUE "FileVersion", "0.1.0"\nVALUE "ProductVersion", "0.1.0"\n',
            encoding="utf-8",
        )
        iss = root / "installer"
        iss.mkdir(parents=True)
        (iss / "iranlink.iss").write_text('#define MyAppVersion "0.1.0"\n', encoding="utf-8")
        (root / "CHANGELOG.md").write_text("## [Unreleased]\n\n### Added\n", encoding="utf-8")
        set_all(root, "1.4.2")
        assert "version: 1.4.2+1" in (root / "pubspec.yaml").read_text()
        assert "FILEVERSION 1,4,2,0" in (rc / "Runner.rc").read_text()
        assert '#define MyAppVersion "1.4.2"' in (iss / "iranlink.iss").read_text()
        dart = (root / "lib" / "src" / "core" / "app_version.dart").read_text()
        assert "kAppVersion = '1.4.2'" in dart
        assert "Release in progress: 1.4.2" in (root / "CHANGELOG.md").read_text()
    print("set_version.py self-test: OK")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Stamp a release version everywhere.")
    ap.add_argument("--version", help="Strict SemVer version, e.g. 1.4.2")
    ap.add_argument("--root", default=".", help="Repository root")
    ap.add_argument("--self-test", action="store_true")
    args = ap.parse_args(argv)
    if args.self_test:
        self_test()
        return 0
    if not args.version:
        ap.error("--version is required (or pass --self-test)")
    set_all(Path(args.root), args.version)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
