/// Diagnostics collection + sanitized report export.
library;

import 'dart:io';

import '../core/app_version.dart';
import '../core/core_manager.dart';
import '../core/port_probe.dart';
import '../logging/log_service.dart';
import '../models/connection.dart';
import '../models/settings.dart';
import '../network/connectivity.dart';
import '../platform/app_paths.dart';
import '../platform/os_info.dart';
import '../proxy/system_proxy.dart';
import '../proxy/tun_manager.dart';
import '../storage/secure_vault.dart';

class PortDiagnostic {
  const PortDiagnostic({
    required this.label,
    required this.port,
    required this.free,
    this.ownerPid,
  });

  final String label;
  final int port;
  final bool free;
  final int? ownerPid;
}

class DiagnosticsReport {
  const DiagnosticsReport({
    required this.collectedAt,
    required this.appVersion,
    required this.os,
    required this.coreVersion,
    required this.coreStatus,
    required this.coreExecutable,
    required this.corePid,
    required this.ports,
    required this.systemProxy,
    required this.tunAvailable,
    required this.tunReason,
    required this.vaultBackend,
    required this.portableMode,
    required this.localAddresses,
    required this.probes,
  });

  final DateTime collectedAt;
  final String appVersion;
  final String os;
  final String coreVersion;
  final CoreStatus coreStatus;
  final String coreExecutable;
  final int? corePid;
  final List<PortDiagnostic> ports;
  final SystemProxyState? systemProxy;
  final bool tunAvailable;
  final String tunReason;
  final String vaultBackend;
  final bool portableMode;
  final List<String> localAddresses;
  final List<ProbeResult> probes;

  String toMarkdown() {
    final buffer = StringBuffer()
      ..writeln('# IranLink diagnostics report')
      ..writeln()
      ..writeln('- Collected: ${collectedAt.toIso8601String()}')
      ..writeln('- App: $appVersion')
      ..writeln('- OS: $os')
      ..writeln('- Core: $coreVersion (${coreStatus.name}, pid=${corePid ?? '-'})')
      ..writeln('- Core binary: $coreExecutable')
      ..writeln('- Vault: $vaultBackend')
      ..writeln('- Portable mode: $portableMode')
      ..writeln('- Local addresses: ${localAddresses.join(', ')}');
    buffer
      ..writeln()
      ..writeln('## Ports');
    for (final port in ports) {
      buffer.writeln(
          '- ${port.label} ${port.port}: ${port.free ? 'free' : 'BUSY (pid=${port.ownerPid ?? '?'})'}',);
    }
    buffer
      ..writeln()
      ..writeln('## Proxy');
    final proxy = systemProxy;
    if (proxy == null) {
      buffer.writeln('- system proxy: unknown (not Windows?)');
    } else {
      buffer.writeln(
          '- system proxy: ${proxy.enabled ? 'enabled' : 'disabled'} server=${proxy.server}',);
    }
    buffer.writeln('- TUN available: $tunAvailable'
        '${tunAvailable ? '' : ' ($tunReason)'}',);
    if (probes.isNotEmpty) {
      buffer
        ..writeln()
        ..writeln('## Connectivity probes');
      for (final probe in probes) {
        buffer.writeln(
            '- ${probe.name}: ${probe.success ? 'OK' : 'FAIL'}'
            '${probe.latencyMs == null ? '' : ' ${probe.latencyMs}ms'}'
            '${probe.detail.isEmpty ? '' : ' (${probe.detail})'}',);
      }
    }
    buffer
      ..writeln()
      ..writeln(
          '> Generated by IranLink. Secrets are never included in this report.',);
    return buffer.toString();
  }
}

class DiagnosticsService {
  DiagnosticsService({
    required CoreManager core,
    required SystemProxyService systemProxy,
    required TunManager tun,
    required SecureVault vault,
    required AppPaths paths,
    required OsInfo os,
    required ConnectivityService connectivity,
    required LogService log,
  })  : _core = core,
        _systemProxy = systemProxy,
        _tun = tun,
        _vault = vault,
        _paths = paths,
        _os = os,
        _connectivity = connectivity,
        _log = log;

  final CoreManager _core;
  final SystemProxyService _systemProxy;
  final TunManager _tun;
  final SecureVault _vault;
  final AppPaths _paths;
  final OsInfo _os;
  final ConnectivityService _connectivity;
  final LogService _log;

  Future<DiagnosticsReport> collect(AppSettings settings,
      {bool runProbes = false,}) async {
    _log.info('diagnostics', 'Collecting report (probes=$runProbes)');
    final inbounds = settings.inbounds;
    final ports = <PortDiagnostic>[];
    for (final entry in [
      ('SOCKS', inbounds.socksPort),
      ('HTTP', inbounds.httpPort),
      if (settings.enableStatsApi) ('stats', settings.statsPort),
    ]) {
      final free = await isPortFree(inbounds.bindAddress, entry.$2);
      ports.add(PortDiagnostic(
        label: entry.$1,
        port: entry.$2,
        free: free,
        ownerPid: free ? null : await findTcpListenerOwner(entry.$2),
      ),);
    }

    SystemProxyState? proxy;
    try {
      proxy = _systemProxy.current();
    } on Object catch (e) {
      _log.debug('diagnostics', 'System proxy unreadable', error: e);
    }

    final tunCap = _tun.capability();
    final addresses = await _localAddresses();

    var probes = <ProbeResult>[];
    if (runProbes) {
      probes = [
        await _connectivity.probeSystemDns('dns.google'),
        await _connectivity.probeTcp('8.8.8.8', 53),
        if (_core.status == CoreStatus.running)
          await _connectivity.probeSocksHandshake(
              inbounds.bindAddress, inbounds.socksPort,),
      ];
    }

    return DiagnosticsReport(
      collectedAt: DateTime.now(),
      appVersion: kAppVersion,
      os: _os.displayName,
      coreVersion:
          _core.coreVersion.isEmpty ? '(unknown)' : _core.coreVersion,
      coreStatus: _core.status,
      coreExecutable: _core.executable.isEmpty ? '(none)' : _core.executable,
      corePid: _core.pid,
      ports: ports,
      systemProxy: proxy,
      tunAvailable: tunCap.available,
      tunReason: tunCap.reasonKey,
      vaultBackend: _vault.backendName,
      portableMode: _paths.portable,
      localAddresses: addresses,
      probes: probes,
    );
  }

  Future<List<String>> _localAddresses() async {
    try {
      final interfaces = await NetworkInterface.list(
          includeLoopback: false, type: InternetAddressType.any,);
      return [
        for (final interface in interfaces)
          for (final address in interface.addresses)
            '${interface.name}: ${address.address}',
      ];
    } on Object {
      return const ['(unavailable)'];
    }
  }
}
